### ISSUE TITLE
Luton Buffer display to LS

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-pack#106]
**Describe the bug**
Luton Buffer displaying to me (LS) when only TCS and ESS is online

**Expected behaviour**
Not to see it

**Screenshots**
![image](https://user-images.githubusercontent.com/12017284/107076031-d6444400-67e2-11eb-8c33-b4e060a1b7b2.png)

**Comment by luke11brown** [comment]
This feature has been requested by Erik as well ref: https://vatsim-scandinavia.org/forums/topic/4044-and-fuction-on-active-lines-area-maps/

**Comment by hsugden** [comment]
No longer required, as the new Buffer is no longer runway dependent.
