### ISSUE TITLE
iTEC Project

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#146]
**Is your feature request related to a problem? Please describe.**
Prestwick ACC now uses Indra iTEC. Shortly moving to "DPEnroute" Still in development.

**Describe the solution you'd like**
 Implement a simulation of this.

**Is your suggestion based on a real world display?**
Yes, Prestwick upper area sectors. DPLower will be implemented after for STC secors, replacing NODE

**Additional context**
Very similar to TopSky, colours are rather different. Maybe in use within VATGER.
A possible adaptation of EDUU of EDGG PRO CTR setups?

**Comment by cbyworth** [comment]
![Screenshot_20210808-130217](https://user-images.githubusercontent.com/45854780/128631297-bd00122f-7c35-437b-b3bd-21e9828792b4.png)
![650px_Craig-Thomson-controlling-first-iTEC-flight](https://user-images.githubusercontent.com/45854780/128631306-a3456dbf-cb47-44ea-b1b9-193df55f3714.jpg)

Some hopefully useful reference images
