### ISSUE TITLE
Update Airlines file for vSMR

### ISSUE THREAD

**Issue by GeekPro101** [VATSIM-UK/uk-controller-pack#213]
The ICAO_Airlines.txt file in UK/Data/Plugins/vSMR should be updated each AIRAC - it is currently on 2021/01.

**Comment by WillShaw1100** [comment]
@GeekPro101 Quick job, Ill do this, this cycle.

**Comment by luke11brown** [comment]
Will complete when others are done as part of release tasks

**Comment by luke11brown** [comment]
Fixed in #220
