### ISSUE TITLE
Change displayed labels at EGLC

### ISSUE THREAD

**Issue by GeekPro101** [VATSIM-UK/uk-controller-pack#218]
# Changes
SMR changes at EGLC:

- [x] New T1 - T6 holds
- [x] W and Y holds removed

# Link to AMDT or Sector File issue/pr (page number on PDF)
Issue: [https://github.com/VATSIM-UK/UK-Sector-File/issues/3701](https://github.com/VATSIM-UK/UK-Sector-File/issues/3701)
PR: [https://github.com/VATSIM-UK/UK-Sector-File/pull/3834](https://github.com/VATSIM-UK/UK-Sector-File/pull/3834)

# Files to be changed
/UK/Data/ASR/TC_APP/Generic SMR.asr
/UK/Data/ASR/Thames/City SMR.asr
/UK/Data/ASR/LTC/City SMR.asr
/UK/Data/ASR/AC_S/City SMR.asr

**Comment by luke11brown** [comment]
Fixed in #220
