### ISSUE TITLE
Incorporate UKCP Go-Around Alam

### ISSUE THREAD

**Issue by cbyworth** [VATSIM-UK/uk-controller-pack#222]
**Is your feature request related to a problem? Please describe.**
Incorporate UKCP Go-Around Alarm for profiles

**Describe the solution you'd like**
The pack will include appropriate default set-up for UKCP Go-Around alarm including where an alarm occurs for a missed approach at an adjacent airfield that is operationally significant for the controller.

**Is your suggestion based on a real world display?**
Real world feature.
For most places this will be an alarm to all APC positions.
There are some places IRL where an alarm is shared to adjacent positions.

Heathrow alarm sounds at:
1. TC Heathrow
2. TC Thames (as controlling low-level S/VFR traffic)
3. Northolt APC - they must restrict any outbound traffic to 2000 ft and then coordinate with TC LL INT N
4. Farnborough APC - they have to coordinate with TC LL INT S in the event they have traffic holding at VEXUB or if, from radar monitoring, an inbound/outbound is liable to conflict with the Heathrow go-around traffic

I suspect there might be a few other places where this is useful. Thoughts @hsugden ?

**Comment by hsugden** [comment]
Yes I would've thought:
- Cardiff & Bristol in certain runway configs?
- Aldergrove Radar for City go arounds - maybe?
- Essex (for now...)

**Comment by cbyworth** [comment]
I've checked with our sources.
Aldergrove gets City.
Bristol and Cardiff only get their own.
Agree with Essex (for now 😭)

Others:
Solent should get Bournemouth only when covering top-down
Likewise Thames should get Southend only when covering top-down (I don't think Biggin would have one IRL but I'm not against adding one on the pack)

**Comment by luke11brown** [comment]
Not sure how we can control it with this level of granularity. For example, if you're using a TC profile, the settings will make it so you receive a go around alarm for all TC covered airports. The same with Area, if covering Bandbox you will receive every single go around alarm in the FIR.

**Comment by KHardern** [comment]
Discussed internally in operations. Summary:
- new UKCP logic expected at next release (3.13)
- 'when providing services' (tower/fin/app) relate to coverage actually being provided
- missed approach airfield list for overriding when not controlling top down

Comitted all changes here:
https://github.com/VATSIM-UK/uk-controller-pack/pull/229

I have included the following 'overriding' alarms:
EGWU for EGLL
EGWU/EGLL/EGLF for Thames radar profiles
EGSY for EGFF and vice-versa
EGNR for EGGP

Others on here don't have specific profiles (e.g. EGAA/AC, EGLF) and therefore not written in currently.
Let me know if any issues @luke11brown @cbyworth
