### ISSUE TITLE
README instructions regarding the Visual C++ Redistributable installation are unclear

### ISSUE THREAD

**Issue by paulstimpson** [VATSIM-UK/uk-controller-pack#251]
**Describe the bug**
README instructions regarding the Visual C++ Redistributable installation are unclear

**To Reproduce**
1. Follow the instruction in the README to download the VC++ Redis from [https://aka.ms/vs/15/release/VC_redist.x86.exe](https://aka.ms/vs/15/release/VC_redist.x86.exe)
2. Attempt to install it on a Windows 10 machine with a lot of existing VC++ Redis installs of varying versions (some appearing to be newer)
3. Observe message from the Redis installer telling you to remove the existing version
4. Experience confusion on how to get the plugin running and whether the existing Redis versions are adequate or whether you really need to break other software by removing the other versions

**Expected behavior**
The instructions would state which versions of the VC++ Redis are acceptable and what to do if the above conflict arises during install.

**Screenshots**
Versions of the Redis already installed: 
![image](https://user-images.githubusercontent.com/2911040/154556365-0529663f-7c53-42a2-97f1-9dee8d8f1459.png)

Error from Redis installer referenced in the README:
![image](https://user-images.githubusercontent.com/2911040/154556610-0a4cae61-c97e-4675-a72e-bdb6eec8a93e.png)

**EuroScope Version:**
 - 3.2

**Additional context**
N/A

**Comment by hsugden** [comment]
Thanks, I have added a note that 2022+ is the version required to the next README addition
