### ISSUE TITLE
AFIS/AG profile (Flight Information Display - FID)

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-pack#290]
## Is your feature request related to a problem? Please describe.
There is currently no profile tailored specifically for providing an A/G or AFIS service.

## Describe the solution you'd like
Add profile(s) with:
- Custom lists containing the most useful information
- Custom Voice.txt and Profiles.txt files to include all 'approved' positions (for discussion with @cbyworth)
- Custom symbology etc.
- Flight Information Display (FID)
- Ground View

## Is your suggestion based on a real world display?
[SimpliFID](http://www.simplifid.aero/)

[Barton Trial](https://www.suasnews.com/2019/09/airspace4all-ga-airfield-ats-ads-b-traffic-display-trial-at-barton-to-continue-until-30-april-2020/)

## Additional context
See [CAP 670 SA 2021/02](https://publicapps.caa.co.uk/docs/33/CAP670%20SA%202021-02.pdf) - Cooperative Surveillance Systems & Flight Information Displays

**Comment by hsugden** [comment]
@danielbutton @PLM1995

This may also be relevant at some point - https://github.com/VATSIM-UK/uk-controller-plugin/issues/173

**Comment by danielbutton** [comment]
I am going to Kemble in June for AeroExpo, will see if I can sneak into the TWR and have a look around.

I have a TAG set and vSMR profile that I use for AFIS/AG/Procedural APP if that would be of any use 🙂 TAGs only show callsigns and vSMR labels show a callsign with A/C type and changes colour when a plane is using the runway. I also have custom symbology that I can donate, based on the Heathrow ATM Symbology set.
