### ISSUE TITLE
Filthy batch file to add user details to various places

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#317]
**Is your feature request related to a problem? Please describe.**
User details not entered into various bits of ES...

**Describe the solution you'd like**
batch file to enter the following:
 Insert Hoppie Code to TopSky/vSMR
Insert Name/CID (probably not password) to login screen and VCCS nickname

Or other method that someone else can think of...

**Comment by SamLefevre** [comment]
I'd be happy to try this as I believe I found a way to do this.
