### ISSUE TITLE
2210 ENR 6-81 (area minimum altitudes) review

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#322]
# Changes

Check current ENR6-7 against TopSKyMSAW data.

# Link to AMDT or Sector File issue/pr (page number on PDF)

ENR6-7

# Files to be changed
/Data/Plugin/TopSkyMSAW.txt

**Comment by MikePike-collab** [comment]
Want me to review general minimum alts. (ENR 6-81) which I contributed originally?

**Comment by luke11brown** [comment]
> Want me to review general minimum alts. (ENR 6-81) which I contributed originally?

6-81 is the chart I meant! Feel free

**Comment by MikePike-collab** [comment]
Here's the file updated to AIRAC 2022/10. (just the ENR 6.81 references.)
[TopSkyMSAW.txt](https://github.com/VATSIM-UK/uk-controller-pack/files/9693799/TopSkyMSAW.txt)

**Comment by luke11brown** [comment]
> Here's the file updated to AIRAC 2022/10. (just the ENR 6.81 references.) [TopSkyMSAW.txt](https://github.com/VATSIM-UK/uk-controller-pack/files/9693799/TopSkyMSAW.txt)

#323 created
