### ISSUE TITLE
Set default leader line to 1 min

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-pack#356]
**Is your feature request related to a problem? Please describe.**
Leader lines based on miles should not be the default - minutes!!

**Describe the solution you'd like**
Edit all radar ASRs (including Area, but not ATMs) to use 1 min leader lines as the default

**Comment by PLM1995** [comment]
Do you want to just adjust the length of the leader lines, or also enable them by default?
