### ISSUE TITLE
Logon details: Improve coverage and build on GitHub

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#500]
## What is the current situation?
Compiled exe, requested to be compiled via GitHub action on this repo, alongside the addition of the following features

## What is the proposed change?
Compile exe using GH action
Insert in addition to the already included fields

- Controller rating
- OBS callsign into ESE file (for alt ownership)
- Datablock symbology font size (large screens and tired, old eyes)
- If no Hoppie code, point user in the direction of creating one

**Comment by PLM1995** [comment]
The OBS callsign - could that also be added to the profile files' logon profile things, so it's selectable from the drop-down?

**Comment by luke11brown** [comment]
@CalumTowers exe is built using PyInstaller

options are `--icon --onefile`
