### ISSUE TITLE
Settings: Separate screen settings for APP vs. SMR

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-pack#509]
## What is the current situation?
SMR/ATM/APP profiles sometimes share a screen settings file, so you can't save them being on different screens

## What is the proposed change?
Ensure that different _types_ of profile use unique screen settings

## Reference materials (e.g. screenshots)
None

## Additional context
https://discord.com/channels/705488311346790471/799666924002345060/1150071695302987786

and 

https://discord.com/channels/705488311346790471/799666924002345060/1150389315797524520

**Comment by luke11brown** [comment]
@hazzas-99 Bit late to the party bro? https://github.com/VATSIM-UK/uk-controller-pack/issues/24

**Comment by luke11brown** [comment]
My suggestion is we standardise the naming of the profiles to the following:
<Airport>
<Airport SMR>
<Airport ATM>

Remove all the combined etc. etc.

Users with one screen load the <airport> profile, users with two screens load the <airport SMR> profile as well.

e.g.
Gatwick
`Contains the 1-4 APP displays, lists etc. with the option of the SMR on F1+5`

Gatwick SMR
`Just the SMR with it's own screen/list settings`

Gatiwick ATM
`Just the ATM with very limited lists etc.`
