### ISSUE TITLE
Create/Include Belfast Profiles

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#54]
**Is your feature request related to a problem? Please describe.**
No Belfast profiles, requires creating

**Describe the solution you'd like**
Create:
- PRF
- ASR
- Settings
- Use Approach tag style
- -Include controller info lines (AAR covers UKFIS in NI)

**Is your suggestion based on a real world display?**
Possible ref images here: http://www.niaviation.co.uk/index.php?topic=11689.0

**Additional context**
NIL

**Comment by PLM1995** [comment]
I'd like to have a crack at this as my first contribution to the controller pack. Which tag style is it now as I don't think Approach exists anymore? NOVA 9000?
