### ISSUE TITLE
EuroScope 3.2.7 Settings

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#621]
### GEN SET -> Zoom in background thread

Set to unticked (can be set to on if performance issues encountered)

Saved in Screen.txt and Screen_SMR.txt

`BackgroundGrphicsInThread:0`

### Set path and include AircraftPerformance.txt

Path defined like ICAO datafiles in .prfs
`Settings	performance`

**Comment by AliceFord** [comment]
Is it meant to be `BackgroundGrphicsInThread:0` or Gr*a*phics?

**Comment by luke11brown** [comment]
I copied this from what it saved, so I think it's actually grphics 😂
