### ISSUE TITLE
Setup & configure VCH plugin

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#637]
## What is the current situation?
VCH not set up

## What is the proposed change?
VCH included set-up (columns hidden)

## Reference materials (e.g. screenshots)
https://github.com/DrFreas/VCH

**Comment by RedstonePilot** [comment]
Can do this

**Comment by RedstonePilot** [comment]
I've added to most of the relevant lists but should the CTL flag be in the dep and relevant lists for lines ups or just the arrival lists?
