### ISSUE TITLE
Split lists GND STS non-sequential changes

### ISSUE THREAD

**Issue by PLM1995** [VATSIM-UK/uk-controller-pack#644]
## What is the current situation?

When using the split lists, if you mis-click an advanced ground status option, the 'strip' pings to another list and you can't get it back (as the advanced options only let you itterate the strip forwards). Likewise if you want to jump a strip multiple lists at once it takes many clicks going through each option.

## What is the proposed change?

Change the **right click** functionality of the split lists GND STS collum to `Open Ground Status Popup List` rather than the advanced equivalent, to enable movement of the strip in a non-linear way if required.

## Additional context

This will obviously need doing to both the normal and Heathrow SMR lists.

Might be worth waiting for #643 to be merged to avoid possible conflicts?

**Comment by RedstonePilot** [comment]
Since I'm also working on #643 I don't mind also doing this

**Comment by luke11brown** [comment]
Closed in #413
