### ISSUE TITLE
Generic profiles: error opening "Generic_Profiles.txt"

### ISSUE THREAD

**Issue by PaulWalkerUK** [VATSIM-UK/uk-controller-pack#651]
## What is the bug?
When loading either the `Generic SMR.prf` or `Generic Radar.prf` profiles, I get the error:

> Error: File open error: C:\Users\Paul\AppData\Roaming\EuroScope\UK\Generic\..\Data\Settings\TC_APP\Generic_Profiles.txt

## How to reproduce?
1. Load either the `UK\Generic\Generic SMR.prf` or `UK\Generic\Generic Radar.prf` profiles
2. Check Messages pane

* Which Profile? `Generic SMR.prf` or `Generic Radar.prf`
* Where have you installed the pack to? `%APPDATA%\EuroScope`
* Have you edited any settings from default? No
* Do you have an up to date sector file? Yes

## EuroScope Version
3.2.3

**Comment by luke11brown** [comment]
Thanks for the report.

Given the generic nature of the profile, I think I'll just create a blank file.

Planned for 2024/04

**Comment by luke11brown** [comment]
Fixed in 45d33026878c82fbbae6415ec82ee5940fd749e0
