### ISSUE TITLE
Kirkwall (EGPA) ATIS freq changed to 124.130 since AIRAC 2401

### ISSUE THREAD

**Issue by PLM1995** [VATSIM-UK/uk-controller-pack#656]
# Changes

Change ATIS definition in scottish voice to 124.130

# Link to AMDT or Sector File issue/pr (page number on PDF)

https://www.aurora.nats.co.uk/htmlAIP/Publications/2024-04-18-AIRAC/html/eAIP/EG-AD-2.EGPA-en-GB.html#EGPA-AD-2.18

# Files to be changed
[Voice_Scottish.txt](https://github.com/VATSIM-UK/uk-controller-pack/blob/main/UK/Data/Settings/Voice_Scottish.txt)

**Comment by luke11brown** [comment]
Fixed in b689d6c0580f5c1605f0d4173a9f917f52b3a087

**Comment by luke11brown** [comment]
Closed in b689d6c0580f5c1605f0d4173a9f917f52b3a087
