### ISSUE TITLE
Mil Frequency Changes AIRAC 2404

### ISSUE THREAD

**Issue by PLM1995** [VATSIM-UK/uk-controller-pack#687]
# Changes

Various Mil frequencies have been or will be updated in the SF and need updating in the voice settings file.

P.S. I thought tagging the SF PR as CP Change Required would auto-open an issue but it didn't seem to?

# Link to AMDT or Sector File issue/pr (page number on PDF)

Per SF Issues [5277](https://github.com/VATSIM-UK/UK-Sector-File/issues/5277) (PR [5290](https://github.com/VATSIM-UK/UK-Sector-File/pull/5290)); [5278](https://github.com/VATSIM-UK/UK-Sector-File/issues/5278) (PR [5281](https://github.com/VATSIM-UK/UK-Sector-File/pull/5281)); and [5279](https://github.com/VATSIM-UK/UK-Sector-File/issues/5279).

# Files to be changed

/[UK](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK)/[Data](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK/Data)/[Settings](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK/Data/Settings)/Voice_Military.txt

**Comment by kristiankunc** [comment]
I've claimed the remaining SF issue and can do this one as well.
