### ISSUE TITLE
Improving the guide for new users

### ISSUE THREAD

**Issue by EM-Creations** [VATSIM-UK/uk-controller-pack#806]
## What is the current situation?
As a new user I am finding it very hard to understand how to use the plugin and which profiles to choose etc to reliably load up the application for an area I want to observe.

## What is the proposed change?
I'm happy to improve the PDF / work on a guide for a new user from stratch. It may make sense to long term users of EuroScope and the UK Controller Plugin but I'm having a hard time. Yesterday I managed to get Manchester SMR to work but today I'm totally lost again.

Does anyone have any time to speak to me on Discord / TeamSpeak showing me the setup and common areas where things go wrong, what to do to fix certain situations etc and I'm happy to take detailed notes and fill in gaps on the PDF that currently exists.

## Reference materials (e.g. screenshots)
Discussion with experienced users.

## Additional context
New user.

**Comment by kristiankunc** [comment]
What exactly is it that you're having issues with?
The PDF links to an observer guide which pretty seems sufficient to me and goes into quite a lot of detail.

> Yesterday I managed to get Manchester SMR to work but today I'm totally lost again.
Loading up Manchester SMR should be as easy as opening the file on starup and connecting, not much more to it. All is described in the observer guide

**Comment by luke11brown** [comment]
Of course, you are welcome to submit an amendment to the README.pdf on here for peer review.

We also have material on the VATSIM UK moodle which I has already been looked at for an update. Awaiting upload from the ATC training team.

Finally alongside comments from @kristiankunc we have a video to explain everything in the readme, for those that prefer watching, rather than reading, which is also pending an update. https://www.youtube.com/watch?v=PAsuAfHsJoQ

**Comment by EM-Creations** [comment]
> What exactly is it that you're having issues with? The PDF links to an observer guide which pretty seems sufficient to me and goes into quite a lot of detail.
> 
> > Yesterday I managed to get Manchester SMR to work but today I'm totally lost again.
> 
> Loading up Manchester SMR should be as easy as opening the file on starup and connecting, not much more to it. All is described in the observer guide

I'm happy to see with you on TeamSpeak or Discord and you watch what I do and see where I'm going wrong having read the README but I can't get it to consistently work. I must be doing something wrong that is assumed by writers of the README or something.

I'm happy to make amendments and help but I need to first spend time with someone who understands it inside and out if that can be arranged please? :)

**Comment by EM-Creations** [comment]
> @EM-Creations You'd be better to find help in the discord if you open a thread in community support.

Yup I watched that video today it was a great help thanks. I have discovered that the root of most of my problems were that it turns out you need to restart EuroScope if you want to open another sector file. Now it works correctly so long as I restart between switching profiles. This really wasn't obvious as the application makes it look like it's easy to switch between them and not an issue.

There are still a few changes I think could be made to the readme, so I may raise a PR soon. :)

Feel free to close this issue #806, thanks everyone.
