### ISSUE TITLE
TopSky Included in NODE profiles

### ISSUE THREAD

**Issue by quassbutreally** [VATSIM-UK/uk-controller-pack#817]
## What is the bug?
```NODE profiles should not include TopSky as a plug-in```

## How to reproduce?
```
Steps to reproduce the behavior:
1. Load any London TC profile
2. Observe
```

## Screenshots

![image](https://github.com/user-attachments/assets/8c50a6b2-d6f1-48ec-87c0-c303fbd4a69c)

## EuroScope Version
`e.g. 3.2.9`

## Additional context
`pls fix <3`

**Comment by luke11brown** [comment]
Are you sure dear?

https://github.com/VATSIM-UK/uk-controller-pack/issues/751

I've just spent the last 4 weeks putting it into NODE and NOVA displays to allow display of part time airspace, AUP activations etc.

In the next go at it, I'm looking to add some safety nets to the above e.g. CLAM/RAM/MSAW etc.

**Comment by quassbutreally** [comment]
That’s all well and good but can we not have the topsky menu at the top? No
me gusta.

**Comment by luke11brown** [comment]
> That’s all well and good but can we not have the topsky menu at the top? No me gusta.

Don't think it's possible chief. Not to say that I've missed something in th TopSKy dev guide or settings though. But I doubt the toolbar is something that can be hidden.

**Comment by SamLefevre** [comment]
![image](https://github.com/user-attachments/assets/cacca98b-0729-4ae5-851f-cd1088421efa)
I've adjusted my TopSky colours

```
//Signs TopSky in on callsign change to determine colours and other settings.
Setup_AutoSignIn=1

//Darker colour palette for TopSky UI. Delete these lines if you like the lighter grey.
//Color_Background=38,38,38
//Color_Border=19,19,19
//Color_WM_Bg=81,81,81
//Color_WM_Border=54,54,54
//Color_WM_Fg=200,200,200

Color_Background=0,0,0
Color_Border=10,10,10
Color_WM_Bg=169,109,99
Color_WM_Border=10,10,10
Color_WM_Fg=255,255,255
```

Into TopSkySettingsLocal.txt
