### ISSUE TITLE
CID Autofill in feedback link

### ISSUE THREAD

**Issue by AliceFord** [VATSIM-UK/uk-controller-pack#829]
## What is the current situation?
Currently we have the feedback link in the controller information, `vats.im/atcfb`.

## What is the proposed change?
Use the vatsim.uk link with the ?cid parameter to autofill the CID (e.g. `vatsim.uk/atcfb?cid=1646235`) as getting the CID seems to be something of an issue for some pilots wishing to put in feedback. Then just add this to the `LogonDetails.py` script.

Thoughts @luke11brown ?

**Comment by luke11brown** [comment]
Sounds like a good idea

**Comment by BenWalker01** [comment]
Can do this if needed.
