### ISSUE TITLE
Additional Wallop Alias'

### ISSUE THREAD

**Issue by Lucak1011** [VATSIM-UK/uk-controller-pack#839]
## What is the current situation?
There is currently only 2-3 Alias' for walloping pilots. 

## What is the proposed change?
I've created some more in depth alias' to wallop pilots to increase efficiency when controlling.

## Reference materials (e.g. screenshots)
Current: 
![image](https://github.com/user-attachments/assets/7a08fca5-0d1f-4325-97db-6a7b503e2129)

Proposed changes:
![image](https://github.com/user-attachments/assets/771de0d1-e933-4476-8db8-7fe845b2301f)

## Additional context
This is my current stance with this Feat. Request. Any additional suggestions, do let me know!

**Comment by Lucak1011** [comment]
> As a supv - I would say even just saying "$aircraft is in breach of CoC B8(A) please assist - further info $1" would probably be ok - supervisors are mainly looking to know what the issue is, the callsign and how they can assist you - if you refer to the part of the CoC we can get you help faster. Some wallops need more info - like what time you started calling them on PM, or what they're specifically unable to do, but most we can just handle with your callsign, the c/s of the plane and the part of the CoC we need to handle.

Thanks for the input - Chris! I'll have a look at changing them!

**Comment by BenWalker01** [comment]
Not for walloping, but perhaps one for a link to simbrief, `.sb`

**Comment by SamLefevre** [comment]
I can't remember every different A/B/C code for each of the code of conduct so can we use .wsomething instead still? I imagine those who aren't SUPs as well wouldn't know B2 is for paused.

**Comment by Lucak1011** [comment]
Closing as lost all proposed changes + more in pack update as forgot to save. May re-open at a later date when I have more time.
