### ISSUE TITLE
2409 MIL Frequency Changes

### ISSUE THREAD

**Issue by PLM1995** [VATSIM-UK/uk-controller-pack#843]
# Changes

8.33kHz-ing 3 ADs. See SF issues below

# Link to AMDT or Sector File issue/pr (page number on PDF)
https://github.com/VATSIM-UK/UK-Sector-File/issues/5428
https://github.com/VATSIM-UK/UK-Sector-File/issues/5430
https://github.com/VATSIM-UK/UK-Sector-File/issues/5431

# Files to be changed
[UK](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK)/[Data](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK/Data)/[Settings](https://github.com/VATSIM-UK/uk-controller-pack/tree/main/UK/Data/Settings)/Voice_Military.txt

**Comment by BenWalker01** [comment]
Will do this :)
