### ISSUE TITLE
Add Edinburgh ATM profile

### ISSUE THREAD

**Issue by frazerxyz** [VATSIM-UK/uk-controller-pack#885]
## What is the current situation?
Edinburgh currently only has the profiles "Edinburgh" & "Edinburgh SMR"

## What is the proposed change?
Create an Edinburgh ATM profile

## Additional context
Although the difference between the radar screen in the "Edinburgh" profile and an ATM profile would be small, having a dedicated ATM profile means settings & controller setup will be common across most airports.

**Comment by frazerxyz** [comment]
I can do this

**Comment by luke11brown** [comment]
As far as I know (happy to be corrected) the VCR in Edinburgh has the radar screen, there is no dedicated ATM, as all controllers at Edinburgh are ADI & APS rated. This is to allow them to cover tower & approach bandboxed during the night time. This practice is known as radar in the tower (RitT).

Therefore, a dedicated ATM profile is not realistic, nor required.

**Comment by frazerxyz** [comment]
That is also how I understand it, but for those of us that use both the SMR
and ATM profiles on Vatsim, it would be great to have common settings &
workflows across all airports.

**Comment by PLM1995** [comment]
> That is also how I understand it, but for those of us that use both the SMR and ATM profiles on Vatsim, it would be great to have common settings & workflows across all airports.

Forgive me if I'm missing the point, what's wrong with using the 'Radar' profile as an ATM in this instance? I have never had problems using it as such personally.

Not sure on your thoughts on this Luke, but would a `Generic ATM.prf` be more appropriate perhaps? Rather than an unrealistic EDI specific one.

**Comment by SamLefevre** [comment]
Imo a Generic ATM.prf would be just another set of symbology ASR we have to add to the controller pack when a normal Generic Radar or Aerodrome specific Radar would work fine.

**Comment by luke11brown** [comment]
Closing, the solution is using the radar screen as the ATM.
