### ISSUE TITLE
Automations: AIRAC actions still tries to Update non UK_* sector files

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-pack#919]
## What is the bug?

.sct files that don't start with UK_* should not be updated e.g. Akrotiri sector file

## How to reproduce?
https://github.com/VATSIM-UK/uk-controller-pack/actions/runs/12079012315

**Comment by 19wintersp** [comment]
Oversight on my part in suggesting that regex, thought it was a relative path 😅 replacing the `UK` with `UK_` or `\\UK` (check number of required escapes with Python) should work
