### ISSUE TITLE
Outdated Copenhagen CPDLC logon codes

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-pack#925]
## What is the bug?

Following the new LoA, CPDLC logon codes for Copenhagen interface are now out of date.

They should be:

EKDK_N (CN) - EKDN
EKDK_UN (CUN) - EKDU
EKDK_V (CV) - EKDV
EKDK_WE (CWE) - EKDW
EKDK (C) - EKDK

**Comment by AdriTheDev** [comment]
Can take
