### ISSUE TITLE
Waddington (EGXW) Frequency changes

### ISSUE THREAD

**Issue by PLM1995** [VATSIM-UK/uk-controller-pack#928]
# Changes

Update mill voice to match changes made in https://github.com/VATSIM-UK/UK-Sector-File/pull/5533

NOTE: Wait until final decision is made on the LARS/APP frequency implementation, we might be adding a new position/callsign as well as updating to 8.33kHz spacing.

# Link to AMDT or Sector File issue/pr (page number on PDF)

SF PR: https://github.com/VATSIM-UK/UK-Sector-File/pull/5533

# Files to be changed
UK/Data/Settings/Voice_Military.txt

**Comment by AdriTheDev** [comment]
Can take

**Comment by PLM1995** [comment]
Thanks @AdriTheDev, we can now proceed with this. New position + frequency changes
